# Homework 9 computational problems

## Problem 1: the functional calculus

One important application of the eigendecomposition $A = U\Lambda U^\top$ of symmetric matrices $A$ is that it allows us to easily compute matrix powers. For example, we have

$$
A^2 = AA = U\Lambda \underbrace{U^\top U}_I\Lambda U^\top = U\Lambda^2 U^\top
$$

or more generally,

$$
A^k = U\Lambda^k U^\top.
$$

Since $\Lambda$ is diagonal, computing the $k$th power $\Lambda^k$ is easy: we just take the $k$th power of each of the diagonal elements. This immediately allows us to compute other functions of a matrix.

Let $f(x)$ be a function taking the following form, for scalars $a_0,a_1,a_2,\dots$:

$$
f(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \cdots = \sum_{k=0}^\infty a_k x^k
$$

Then for a matrix $A$, we define $f(A)$ as follows:

$$
f(A) = \sum_{k=0}^\infty a_k A^k.
$$

Since $A^k = U \Lambda^k U^\top$, we have

$$
f(A) = \sum_{k=0}^\infty a_k A^k =  \sum_{k=0}^\infty a_k U \Lambda^k U^\top = U \left( \sum_{k=0}^\infty a_k \Lambda^k\right) U^\top = U f(\Lambda) U^\top.
$$

This allows us to compute $f(A)$ for any function $f(x)$ of the form $\sum_{k=0}^\infty a_k x^k$ and symmetric matrix $A$. This method is called the _functional calculus_. In this problem, we will look at a few examples of how it can be used. For this problem, we will use the matrix $A$ defined below:

In [1]:
import numpy as np

n = 10
A = np.random.normal(size=(n,n))
A = np.dot(A.T, A)

### Part A: powers of matrices
One simple example of the function calculus is using it to compute powers of matrices. Recall that for an $n\times n$ matrix $A$, by $A^k$ we mean the $k$-fold matrix product $A\cdots A$. Use the functional calculus approach to compute $A^k$ for by computing $A^k = U\Lambda^k U^\top$, for $k=5$.

In [7]:
Lambda, V = np.linalg.eig(A)
Lambda = np.diag(Lambda)
print(Lambda)

[[3.45253782e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.86234976e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.26157822e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.46893571e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  6.57892103e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 4.13123428e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e

In [6]:
k = 5

Ak = A@A@A@A@A
Ak

array([[   855962.41868747,  -3032041.04697571,     77615.28427082,
         -1791101.29070877,  -1607990.07484917,    937455.34082224,
           407939.54354546,  -1012178.73544088,  -3610186.04256653,
          1845078.32566878],
       [ -3032041.04697571,  13792166.85889721,   -207491.27999187,
          7308546.63649698,   7257029.64111896,  -4043282.07806358,
         -1095131.7697954 ,   4277977.94813323,  16045928.0161974 ,
         -8715818.78977868],
       [    77615.28427082,   -207491.27999187,     28643.87904276,
           -79549.4149334 ,   -149586.7475238 ,     95236.35170476,
            40049.35836037,    -54493.28360577,   -272585.07123897,
           120715.59962386],
       [ -1791101.29070877,   7308546.63649698,    -79549.4149334 ,
          4807739.85215539,   3308609.90220186,  -1874995.57070855,
         -1146724.84880142,   2799619.00316913,   8349173.41724532,
         -4261995.52227881],
       [ -1607990.07484917,   7257029.64111896,   -149586.7475238 ,


In [11]:
np.allclose(Ak, Ak_2)

True

In [10]:
Lambda_k = Lambda**k
Ak_2 = V@Lambda_k@V.T
Ak_2

array([[   855962.41868747,  -3032041.04697571,     77615.28427082,
         -1791101.29070877,  -1607990.07484916,    937455.34082223,
           407939.54354546,  -1012178.73544088,  -3610186.04256651,
          1845078.32566877],
       [ -3032041.04697571,  13792166.85889716,   -207491.27999187,
          7308546.63649696,   7257029.64111894,  -4043282.07806356,
         -1095131.76979539,   4277977.94813322,  16045928.01619734,
         -8715818.78977865],
       [    77615.28427082,   -207491.27999187,     28643.87904276,
           -79549.4149334 ,   -149586.7475238 ,     95236.35170476,
            40049.35836037,    -54493.28360577,   -272585.07123897,
           120715.59962386],
       [ -1791101.29070877,   7308546.63649696,    -79549.4149334 ,
          4807739.85215537,   3308609.90220185,  -1874995.57070854,
         -1146724.84880141,   2799619.00316912,   8349173.41724529,
         -4261995.5222788 ],
       [ -1607990.07484916,   7257029.64111894,   -149586.7475238 ,


### Part B: the matrix exponential

Recall that the function $f(x) = e^x$ can be written as $e^x = \sum_{k=0}^\infty \frac{1}{k!}x^k$; therefore, the method described above applies. Use the functional calculus approach to compute $f(A) = e^A$, for the matrix $A$ defined above. 

In [13]:
expLambda = np.exp(Lambda)
expA = V@expLambda@V.T
expA

array([[ 1.39961870e+13, -6.22293707e+13,  1.00194860e+12,
        -3.29453919e+13, -3.30178873e+13,  1.84743854e+13,
         4.97166767e+12, -1.91936755e+13, -7.26605221e+13,
         3.93823861e+13],
       [-6.22293707e+13,  2.76682140e+14, -4.45483090e+12,
         1.46480661e+14,  1.46803044e+14, -8.21402033e+13,
        -2.21048387e+13,  8.53382550e+13,  3.23060782e+14,
        -1.75100659e+14],
       [ 1.00194860e+12, -4.45483090e+12,  7.17268198e+10,
        -2.35846902e+12, -2.36366156e+12,  1.32253141e+12,
         3.55907039e+11, -1.37402184e+12, -5.20156893e+12,
         2.81927831e+12],
       [-3.29453919e+13,  1.46480661e+14, -2.35846902e+12,
         7.75496300e+13,  7.77202263e+13, -4.34865328e+13,
        -1.17027437e+13,  4.51796857e+13,  1.71034365e+14,
        -9.27015183e+13],
       [-3.30178873e+13,  1.46803044e+14, -2.36366156e+12,
         7.77202263e+13,  7.78913262e+13, -4.35822655e+13,
        -1.17284486e+13,  4.52790723e+13,  1.71410803e+14,
        -9.

### Part C: the matrix logarithm
Let $g(x) = \log(x)$. As long as the eigenvalues of $A$ are strictly positive, we can use the functional calculus to compute $g(A)$. 
Use the functional calculus to compute $g(A) = \log(A)$. Then, also using the functional calculus, compute $f(g(A)) = e^{\log(A)}$, where $f$ is as given in part B. What matrix do you get?

In [ ]:
log_expA = V@log_expLambda@V.T