# The QR algorithm for finding eigenvalues and eigenvectors

In the previous sections, we discussed finding the eigenvalues and eigenvectors of a matrix $\boldsymbol{A}$ largely abstractly, without much interest in how we would actually do this in practice. As we saw, we can find the eigenvalues (in theory) by finding the zeros of the degree-$n$ polynomial $p(\lambda) = \det(\boldsymbol{A} - \lambda \boldsymbol{I})$. If we had these eigenvalues, say $\lambda_1,\dots, \lambda_n$, then we could find the eigenvectors fairly easily by solving the linear system of equations

$$
(\boldsymbol{A} - \lambda_i \boldsymbol{I})\boldsymbol{v} = 0,
$$

e.g. by using the QR decomposition and backsubstitution. The latter component would be a feasible way to find the eigenvectors in practice if we knew what the eigenvalues were. Unfortunately, finding the zeros of $p(\lambda)$ this is not a particularly practical approach, beyond the 2- or 3-dimensional case. Instead, we require other algorithms to find the eigenvalues. We saw one method on the homework for doing this called the _power method_. Here we briefly introduce another popular algorithm which uses the QR decomposition called the QR algorithm, which we outline below.

$$
\begin{align}
&\underline{\textbf{QR algorithm}: \text{find the eigenvalues of an $n\times n$ matrix $\boldsymbol{A}$}} \\
&\textbf{input}:\text{$n\times n$ matrix }\boldsymbol{A}\in \mathbb{R}^{n\times n} \\
&\hspace{0mm} \text{while $\boldsymbol{A}$ is not approximately upper triangular:}\\
&\hspace{10mm} \boldsymbol{Q}, \boldsymbol{R} = \texttt{qr_decomposition}(\boldsymbol{A})\\
&\hspace{10mm} \text{update }\boldsymbol{A} = \boldsymbol{R}\boldsymbol{Q}\\
&\hspace{0mm} \text{return } \text{diag}(\boldsymbol{A})\\
\end{align}
$$

This algorithm works due to the following two properties. First, note that for a single interation we have

$$
\boldsymbol{A}' = \boldsymbol{RQ} = \boldsymbol{Q^\top Q R Q} = \boldsymbol{Q}^\top \boldsymbol{AQ}
$$

where $\boldsymbol{Q}$ is an orthogonal matrix. Because the matrices $\boldsymbol{A}$ and $\boldsymbol{A}'$ differ only by an orthogonal transformation on either side, they are what we call _similar_ matrices. It turns out that similar matrices always have the same eigenvalues. To see this, let $(\lambda, \boldsymbol{v})$ be an eigenvalue/eigenvector pair for $\boldsymbol{A}'$, and let $\boldsymbol{A} = \boldsymbol{Q^\top\boldsymbol{A}'\boldsymbol{Q}}$ be defined as above. Then

$$
\lambda\boldsymbol{v} = \boldsymbol{A}'\boldsymbol{v} = \boldsymbol{QA Q^\top v} \iff \lambda \boldsymbol{Q^\top v} = \boldsymbol{A Q^\top v}.
$$

This means that $(\lambda, \boldsymbol{Q^\top v})$ is an eigenvalue/eigenvector pair for the matrix $\boldsymbol{A}$, and so $\boldsymbol{A}$ and $\boldsymbol{A}'$ have the same eigenvalues, and eigenvectors which differ by a factor of $\boldsymbol{Q}^\top$. Thus at each iteration in the QR algorithm, the matrices $\boldsymbol{A}$ have the same eigenvalues.

The next step we do not prove, but will show numerically. It turns out that for "nice" matrices (in particular, matrices that have distinct eigenvalues), the QR algorithm converges to an upper triangular matrix. Therefore, as we saw in the previous section, we can read off the eigenvalues of this matrix by checking its diagonal entries. Let's see a simple example that illustrates this.

In [1]:
import numpy as np

A = np.random.normal(size= (3,3))
A = np.dot(A.T, A)

for i in range(10):
    Q,R = np.linalg.qr(A)
    A = np.dot(R,Q)
    print('A at iteration i = %s is' % i)
    print(A)

A at iteration i = 0 is
[[ 2.87024658 -1.35464846 -0.38777904]
 [-1.35464846  0.96933605  0.2735415 ]
 [-0.38777904  0.2735415   0.16911072]]
A at iteration i = 1 is
[[ 3.63222975 -0.14297718  0.0107467 ]
 [-0.14297718  0.29100923 -0.02083912]
 [ 0.0107467  -0.02083912  0.08545437]]
A at iteration i = 2 is
[[ 3.63833662e+00 -1.13229445e-02 -2.47592719e-04]
 [-1.13229445e-02  2.86822242e-01  5.97091643e-03]
 [-2.47592719e-04  5.97091643e-03  8.35344881e-02]]
A at iteration i = 3 is
[[ 3.63837466e+00 -8.93225127e-04  5.67489602e-06]
 [-8.93225127e-04  2.86944637e-01 -1.73561781e-03]
 [ 5.67489602e-06 -1.73561781e-03  8.33740574e-02]]
A at iteration i = 4 is
[[ 3.63837489e+00 -7.04499598e-05 -1.30022581e-07]
 [-7.04499598e-05  2.86957948e-01  5.04215643e-04]
 [-1.30022581e-07  5.04215643e-04  8.33605095e-02]]
A at iteration i = 5 is
[[ 3.63837489e+00 -5.55640698e-06  2.97897218e-09]
 [-5.55640698e-06  2.86959090e-01 -1.46471274e-04]
 [ 2.97897193e-09 -1.46471274e-04  8.33593662e-02]]
A at

As we can see, the lower triangular portion of $\boldsymbol{A}$ is becoming closer and closer to zero after more iterations. Hence, since the eigenvalues are unchanged at each iteration, we can read of the eigenvalues of $\boldsymbol{A}$ from the eigenvalues of the (approximately) triangular matrix that we get after several iterations. Let's now implement our own `eigenvalue_decomposition_qr` function which uses the QR algorthm to find the eigenvalues of a matrix $\boldsymbol{A}$.

In [2]:
def eigenvalue_decomposition_qr(A):
    '''
    find the eigenvalues of a matrix using the QR decomposition
    '''
    A0 = A

    # first implement the QR algorithm
    while not np.allclose(A0, np.triu(A0)):
        Q,R = np.linalg.qr(A0)
        A0 = np.dot(R, Q)

    values = np.diag(A0)
    return values

Now let's test our implementation against the usual numpy `eig` function.

In [3]:
A = np.random.normal(size=(5,5))
A = np.dot(A.T, A)

values_qr = eigenvalue_decomposition_qr(A)
print(values_qr)

values, vectors = np.linalg.eig(A)
print(values)

[7.97967959e+00 5.00039847e+00 2.31802664e+00 5.93721729e-01
 4.11825540e-03]
[7.97967959e+00 5.00039847e+00 2.31802664e+00 4.11825540e-03
 5.93721729e-01]


Indeed, the two algorithms give the same output (though potentially not ordered in the same way).